content:
- RUN conda install xeus-cling notebook openmp -c QuantStack -c conda-forge
- RUN sed -i 's/"-std=c++11"/"-std=c++11"\,\n      "-fopenmp"/' /opt/conda/share/jupyter/kernels/xeus-cling-cpp11/kernel.json
- RUN sed -i 's/"-std=c++14"/"-std=c++14"\,\n      "-fopenmp"/' /opt/conda/share/jupyter/kernels/xeus-cling-cpp14/kernel.json
- RUN sed -i 's/"-std=c++17"/"-std=c++17"\,\n      "-fopenmp"/' /opt/conda/share/jupyter/kernels/xeus-cling-cpp17/kernel.json
- RUN wget https://github.com/SpencerPark/IJava/releases/download/v1.2.0/ijava-1.2.0.zip
  && unzip ijava-1.2.0.zip && python3 install.py --sys-prefix && rm -rf ijava-1.2.0.zip
  install.py
- RUN cd /usr/local && wget http://apache.cs.utah.edu/hadoop/common/hadoop-2.9.2/hadoop-2.9.2.tar.gz
  && tar -xvzf hadoop-2.9.2.tar.gz && rm hadoop-2.9.2.tar.gz
- ENV JAVA_HOME=usr/lib/jvm/java-11-openjdk-amd64/
description: ''
name: user-custom-docker
timestamp_utc: '2019-04-02T22:10:23.818151'
